ssn_therapass_admin_login:
    pattern:   /admin/login
    defaults:  { _controller: 'SSNTherapassBundle:Security:login' }
ssn_therapass_admin_login_check:
    pattern:   /admin/login_check
ssn_therapass_admin_logout:
    pattern:   /admin/logout
    
ssn_therapass_login:
    pattern:   /booking/login
    defaults:  { _controller: 'SSNTherapassBundle:Security:loginBooking' }
ssn_therapass_login_check:
    pattern:   /booking/login_check
ssn_therapass_logout:
    pattern:   /booking/logout
